// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.Persistencia;

#nullable disable

namespace SmartHome.Persistencia.Migrations
{
    [DbContext(typeof(ContextoSql))]
    [Migration("20241005211047_AgregoAtributosADispositivoHogar")]
    partial class AgregoAtributosADispositivoHogar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.LogicaNegocio.Dispositivos.Entidades.Dispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("DetectaMovimiento")
                        .HasColumnType("bit");

                    b.Property<bool?>("DetectaPersona")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroModelo")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<bool?>("UsoExterior")
                        .HasColumnType("bit");

                    b.Property<bool?>("UsoInterior")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Dispositivos.Entidades.FotografiaDispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DispositivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.ToTable("FotografiaDispositivo");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.DispositivosHogar.Entidades.DispositivoHogar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DispositivoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaConectado")
                        .HasColumnType("bit");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("HogarId");

                    b.ToTable("DispositivosHogar");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Empresas.Entidades.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Logotipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCreador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Hogares.Entidades.Hogar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CantMiembrosSoportados")
                        .HasColumnType("int");

                    b.Property<Guid>("DueñoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Latitud")
                        .HasColumnType("int");

                    b.Property<int>("Longitud")
                        .HasColumnType("int");

                    b.Property<int>("NumPuerta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DueñoId");

                    b.ToTable("Hogares");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Hogares.Entidades.MiembroHogar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HogarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MiembroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NotificacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("PermisoAsociarDispositivos")
                        .HasColumnType("bit");

                    b.Property<bool>("PermisoListarDispositivos")
                        .HasColumnType("bit");

                    b.Property<bool>("PermisoNotificaciones")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HogarId");

                    b.HasIndex("MiembroId");

                    b.HasIndex("NotificacionId");

                    b.ToTable("MiembrosHogar");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Notificaciones.Entidades.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DispositivoHogarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueLeida")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoHogarId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Usuarios.Entidades.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("030c21ec-8635-48e3-af7e-68fda450daca"),
                            Permisos = "[0]",
                            Tipo = "dueño hogar"
                        },
                        new
                        {
                            Id = new Guid("030c21ec-8635-48e3-af7e-68fda450dacb"),
                            Permisos = "[1,2,3,4,6]",
                            Tipo = "administrador"
                        },
                        new
                        {
                            Id = new Guid("030c21ec-8635-48e3-af7e-68fda450dacc"),
                            Permisos = "[5,7]",
                            Tipo = "dueño empresa"
                        });
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Usuarios.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("030c21ec-8635-48e3-af7e-68fda450dacf"),
                            Apellido = "admin",
                            Contraseña = "admin1234.",
                            Email = "admin@gmail.com",
                            FechaCreacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "admin",
                            RolId = new Guid("030c21ec-8635-48e3-af7e-68fda450dacb")
                        });
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Dispositivos.Entidades.Dispositivo", b =>
                {
                    b.HasOne("SmartHome.LogicaNegocio.Empresas.Entidades.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Dispositivos.Entidades.FotografiaDispositivo", b =>
                {
                    b.HasOne("SmartHome.LogicaNegocio.Dispositivos.Entidades.Dispositivo", null)
                        .WithMany("Fotografias")
                        .HasForeignKey("DispositivoId");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.DispositivosHogar.Entidades.DispositivoHogar", b =>
                {
                    b.HasOne("SmartHome.LogicaNegocio.Dispositivos.Entidades.Dispositivo", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHome.LogicaNegocio.Hogares.Entidades.Hogar", "Hogar")
                        .WithMany()
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");

                    b.Navigation("Hogar");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Hogares.Entidades.Hogar", b =>
                {
                    b.HasOne("SmartHome.LogicaNegocio.Usuarios.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("DueñoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Hogares.Entidades.MiembroHogar", b =>
                {
                    b.HasOne("SmartHome.LogicaNegocio.Hogares.Entidades.Hogar", "Hogar")
                        .WithMany("Miembros")
                        .HasForeignKey("HogarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHome.LogicaNegocio.Usuarios.Entidades.Usuario", "Miembro")
                        .WithMany()
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHome.LogicaNegocio.Notificaciones.Entidades.Notificacion", null)
                        .WithMany("Miembros")
                        .HasForeignKey("NotificacionId");

                    b.Navigation("Hogar");

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Notificaciones.Entidades.Notificacion", b =>
                {
                    b.HasOne("SmartHome.LogicaNegocio.DispositivosHogar.Entidades.DispositivoHogar", "DispositivoHogar")
                        .WithMany()
                        .HasForeignKey("DispositivoHogarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DispositivoHogar");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Usuarios.Entidades.Usuario", b =>
                {
                    b.HasOne("SmartHome.LogicaNegocio.Empresas.Entidades.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId");

                    b.HasOne("SmartHome.LogicaNegocio.Usuarios.Entidades.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Dispositivos.Entidades.Dispositivo", b =>
                {
                    b.Navigation("Fotografias");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Hogares.Entidades.Hogar", b =>
                {
                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("SmartHome.LogicaNegocio.Notificaciones.Entidades.Notificacion", b =>
                {
                    b.Navigation("Miembros");
                });
#pragma warning restore 612, 618
        }
    }
}
